### ISSUE TITLE
Missing Xcode 10.2 support

### ISSUE THREAD

**Issue by tarbayev** [Webtrekk/webtrekk-ios-sdk#55] opened 2019-03-26 15:27 UTC
The SDK depends on [Reachability](https://github.com/ashleymills/Reachability.swift) library, which is configured for Swift 3.0, not supported by Xcode 10.2.

**Comment by MBing** [comment] 2019-04-05 11:30
Version 4.13.2 should fix this. Please check and close if all works fine for you.

Cheers,
Martin

**Comment by MBing** [comment] 2019-04-10 06:08
> this version is generating many build errors

Screenshot?

**Comment by Y2JChamp** [comment] 2019-04-10 10:21
Here it is:
![Schermata 2019-04-10 alle 12 20 18](https://user-images.githubusercontent.com/26578037/55871557-31776200-5b8b-11e9-9876-bb54546d5bba.png)

**Comment by MBing** [comment] 2019-04-10 14:44
@Y2JChamp These errors are unrelated to the update of Reachability. 
We are working on a new version of the SDK which would deal with all these errors.

Currently you can do the following to make sure a release/build still works:
- Project Document -> Project Format => 'Xcode 3.2-compatible'
- File -> Project(Workspace) Settings -> Shared Project Settings -> Build System => 'Legacy Build System'

Then you should be able to build your app again.
When we have the update (v5), we'll let you know of course. 

If this worked for you then we can close this ticket.
(We have it in our backlog as an epic to make all these changes.)

**Comment by Y2JChamp** [comment] 2019-04-10 15:06
still not working...

**Comment by MBing** [comment] 2019-04-10 18:59
> still not working...

and same errors?

**Comment by Y2JChamp** [comment] 2019-04-11 10:02
here's a new screenshot
![Schermata 2019-04-11 alle 12 01 47](https://user-images.githubusercontent.com/26578037/55948860-aca34b80-5c51-11e9-8d2c-b09d871fa996.png)

**Comment by MBing** [comment] 2019-04-11 11:12
I cannot reproduce this when doing the steps as suggested above.

**Comment by Y2JChamp** [comment] 2019-04-11 11:29
I am using CocoaPods

**Comment by MBing** [comment] 2019-04-11 12:05
Ok, so you confirm that using 'Legacy Build System' is not solving your problem?

**Comment by Y2JChamp** [comment] 2019-04-11 13:10
i confirm

**Comment by MBing** [comment] 2019-04-15 06:54
Do you have a sample where you can reproduce this, a minimum implementation, so I can check where what is going wrong? As I can not reproduce it and other clients don't seem to have this problem. This week I am not in the office, but next week I am back. (23rd) So by then I can look into it and otherwise we can schedule a Skype call to dive into the problem.

But it would of course help if you could point me in the right direction. As I know the code is very old and we are working on a new version. Which would help if we gather more info about malfunctions in the old. You can email that sample to me. (my email is in the [.podspec](https://github.com/Webtrekk/webtrekk-ios-sdk/blob/master/Webtrekk.podspec) file)

Thanks and I hope we will find the cause and solve it! 🙂

**Comment by matteomatassoni** [comment] 2019-04-15 09:50
We have the same problems; thus, I tried to fix them and it seems to work. Check out PR #59

**Comment by sebbu** [comment] 2019-04-17 10:20
@MBing It does not matter if it works with the 'Legacy Build System' setting. To require the 'Legacy Build System' is not a solution. We have just started to work on a brand new app (and where actually expecting Swift 5 already).

Could you check @matteomatassoni PR. It looks like he did the necessary work.

Thanks

**Comment by MBing** [comment] 2019-04-23 07:58
@sebbu Since I didn't get an email or any reproducible steps, the best solution was to use the 'Legacy Build System'. The biggest issue with changes and migration is to make sure our other clients don't start complaining of behavior changes. That would cause a lot more problems/costs of course. 

I will have a look at the changes of @matteomatassoni (Thank you for this of course! 😃) , first glance looks like it is just a migration with some name changes, so I need to check if the behavior is still similar. But let's see further in the PRs.

I will get back to you all here ASAP!

**Comment by MBing** [comment] 2019-04-24 15:03
There is a problem with `xcodebuild` (which is used to check/lint verify the code to create a Cocoapod library) and thus I cannot release a version to Cocoapods yet. I am following this: 
https://github.com/CocoaPods/CocoaPods/issues/8729

Which shows others have similar problems, like Apple & Fastlane:
https://bugreport.apple.com/web/?problemID=50093486
https://github.com/fastlane/fastlane/issues/14634

Here's a screenshot of my current output, which shows that the code they check refers to an older platform and thus blocks my upload to create a new version.
![Screenshot 2019-04-24 at 16 53 06](https://user-images.githubusercontent.com/2140223/56670000-53f09b80-66b2-11e9-9204-757e7a7a7edb.png)

**Comment by tarbayev** [comment] 2019-04-25 10:53
FYI, just checked `4.13.2`. Works well with Carthage.

**Comment by MBing** [comment] 2019-04-25 14:20
@tarbayev Thanks for the update! 😃
When using Carthage, you can already use version `4.14.0` already, which should also work with the `New Build System`.

*I will close this ticket once I could update Cocoapods as well.*

**Comment by matteomatassoni** [comment] 2019-06-10 10:15
@MBing do you have any news?

**Comment by MBing** [comment] 2019-06-13 08:12
@matteomatassoni Good news, so there were still some issues with WatchOS, actually a couple due to the migration of 4.2...
Anyway it's fixed and there's a new version on Cocoapods 4.15.3
https://cocoapods.org/pods/Webtrekk

I did have a couple warnings, which I have made a ticket about and will tackle somewhere later. But you should be able to build without a problem. Let me know if all is good.

**Comment by matteomatassoni** [comment] 2019-06-13 13:08
@MBing Thank you; but now we can't use it because iOS's minimum deployment target has been increased from 8.0 to 12.0.

**Comment by MBing** [comment] 2019-06-13 13:58
@matteomatassoni Ah ok, yeah I will revert the .podspec immediately!

**Comment by MBing** [comment] 2019-06-13 14:54
@matteomatassoni updated, can you try and see if it works for you now? The versions should be aligned now, I do have a minimum of 9.0 on both Cocoapods and in Xcode. 4.15.4 is the newest then.

**Comment by matteomatassoni** [comment] 2019-06-13 16:15
@MBing I could not test it right now, but I've already tested it on our fork by reverting the pod spec's minimum to iOS 8.0; thus, I think v4.15.4 works as well. Thank you!

**Comment by MBing** [comment] 2019-06-14 12:09
as everything should work again, I am closing this, let me know if something is off or create a new ticket please.

**Closed by MBing** 2019-06-14 12:09 UTC
